dist: trusty
sudo: false
language: node_js
node_js:
  - "node"
  - "8"
  - "6"
  - "4"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

script: npm run ci

cache:
  yarn: true
  directories:
    - node_modules
    - packages/capnp-ts/node_modules
    - packages/capnpc-ts/node_modules
